name: Build ESP32-S3 Firmware

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt update
        sudo apt install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util
        git clone --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh esp32s3
        echo "source $PWD/export.sh" >> $GITHUB_ENV

    - name: Export IDF
      run: source esp-idf/export.sh

    - name: Build firmware
      run: |
        source esp-idf/export.sh
        idf.py set-target esp32s3
        idf.py build

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: esp32s3-firmware
        path: build/*
